lsi: false
safe: true
source: https://github.com/NaNdaWteK/Filosofia-barata_ia/
incremental: true
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
